### ISSUE TITLE
 webcam_demo.py

### ISSUE THREAD

**Issue by Fedaman-LiFi-ken** [Maelic/SGG-Benchmark#12]
PS F:\SGG-Benchmark\demo> python webcam_demo.py --classes F:\SGG-Benchmark\datasets\vg\VG-SGG-dicts-with-attri.json --config F:\SGG-Benchmark\checkpoints\e2e_relation_X_101_32_8_FPN_1x.yaml --weights F:\SGG-Benchmark\checkpoints\model_0028000.pth --tracking
2024-06-10 12:08:58.521 | INFO     | sgg_benchmark.utils.logger:setup_logger:30 - Using loguru logger with level: INFO
True
2024-06-10 12:09:00.720 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-06-10 12:09:00.720 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-06-10 12:09:00.721 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./output/relation_baseline\VG150_train_statistics.cache
2024-06-10 12:09:00.721 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
F:\anaconda3\envs\scene_graph_benchmark\Lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
2024-06-10 12:09:13.294 | INFO     | sgg_benchmark.utils.checkpoint:load:65 - Loading checkpoint from F:\SGG-Benchmark\checkpoints\model_0028000.pth
Traceback (most recent call last):
  File "F:\SGG-Benchmark\demo\webcam_demo.py", line 63, in <module>
    main(args)
  File "F:\SGG-Benchmark\demo\webcam_demo.py", line 19, in main
    model = SGG_Model(config_path, dict_file, weights, tracking=tracking, rel_conf=rel_conf, box_conf=box_conf)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SGG-Benchmark\demo\demo_model.py", line 61, in __init__
    self.load_model()
  File "F:\SGG-Benchmark\demo\demo_model.py", line 75, in load_model
    ckpt = self.checkpointer.load(self.model_weights)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\sgg-benchmark\sgg_benchmark\utils\checkpoint.py", line 67, in load
    self._load_model(checkpoint, load_mapping, verbose)
  File "f:\sgg-benchmark\sgg_benchmark\utils\checkpoint.py", line 107, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"), load_mapping, verbose)
  File "f:\sgg-benchmark\sgg_benchmark\utils\model_serialization.py", line 94, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "F:\anaconda3\envs\scene_graph_benchmark\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
        size mismatch for roi_heads.relation.predictor.context_layer.untreated_dcd_feat: copying a param with shape torch.Size([4936]) from checkpoint, the shape in current model is torch.Size([5248]).     
        size mismatch for roi_heads.relation.predictor.context_layer.untreated_obj_feat: copying a param with shape torch.Size([4424]) from checkpoint, the shape in current model is torch.Size([4736]).     
        size mismatch for roi_heads.relation.predictor.context_layer.untreated_edg_feat: copying a param with shape torch.Size([4296]) from checkpoint, the shape in current model is torch.Size([4608]).     
        size mismatch for roi_heads.relation.predictor.context_layer.obj_embed1.weight: copying a param with shape torch.Size([151, 200]) from checkpoint, the shape in current model is torch.Size([151, 512]).
        size mismatch for roi_heads.relation.predictor.context_layer.obj_embed2.weight: copying a param with shape torch.Size([151, 200]) from checkpoint, the shape in current model is torch.Size([151, 512]).
        size mismatch for roi_heads.relation.predictor.context_layer.obj_ctx_rnn.weight_ih_l0: copying a param with shape torch.Size([2048, 4424]) from checkpoint, the shape in current model is torch.Size([2048, 4736]).
        size mismatch for roi_heads.relation.predictor.context_layer.obj_ctx_rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 4424]) from checkpoint, the shape in current model is torch.Size([2048, 4736]).
        size mismatch for roi_heads.relation.predictor.context_layer.edge_ctx_rnn.weight_ih_l0: copying a param with shape torch.Size([2048, 4808]) from checkpoint, the shape in current model is torch.Size([2048, 5120]).
        size mismatch for roi_heads.relation.predictor.context_layer.edge_ctx_rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 4808]) from checkpoint, the shape in current model is torch.Size([2048, 5120]).
        size mismatch for roi_heads.relation.predictor.context_layer.decoder_rnn.obj_embed.weight: copying a param with shape torch.Size([152, 200]) from checkpoint, the shape in current model is torch.Size([152, 512]).
        size mismatch for roi_heads.relation.predictor.context_layer.decoder_rnn.input_linearity.weight: copying a param with shape torch.Size([3072, 5136]) from checkpoint, the shape in current model is torch.Size([3072, 5760]).
how to deal with it when I run webcam_demo.py

**Comment by Maelic** [comment]
Hello,

To make it work you'll have to change the key `EMBED_DIM: 512` in the e2e_relation_X_101_32_8_FPN_1x.yaml config file to `EMBED_DIM: 200`.

**Comment by Maelic** [comment]
Close due to inactivity.
