### ISSUE TITLE
Can not find informative_sg.json and zeroshot_triplet.pytorch files

### ISSUE THREAD

**Issue by fullsunhcc** [Maelic/SGG-Benchmark#17]
Hello! Thank you for your great work!
I really happy to see the current torch version of 2D Image Scene graph!! 

On SGG-Benchmark I have two question.
I cannot find the way to find or download  'informative_sg.json' and ' zeroshot_triplet.pytorch' of VG150 in this github.
If I did not give correct directory of the paths_catalog.py , I get this kind of error message.
`FileNotFoundError: [Errno 2] No such file or directory: '/home/uhcc/Desktop/SGG-Benchmark/datasets/vg/informative_sg.json'`

Also, it is okay to train model using single GPU like below command?
`CUDA_VISIBLE_DEVICES=0 torchrun --master_port 10025 --nproc_per_node=1 tools/relation_train_net.py --task sgcls --save-best --config-file "configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 12 TEST.IMS
_PER_BATCH 2 DTYPE "float16" SOLVER.MAX_EPOCH 20 MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR ./checkpoints/motif-precl
s-exmp`

Thank you for your hard work.

**Comment by Maelic** [comment]
Hi, I just added the `zeroshot_triplet.pytorch` file in `datasets/VG150`, you can pull it now and it should work.

Regarding the `informative_sg.json` file, I am not releasing it for now because it is part of another project of mine which is still under review at the time. I may release it later on. You should not have any problem running the code without it, you can deactivate its usage with `TEST.INFORMATIVE False` in your training command (or config file) if you have any trouble.

To train with one GPU you don't need to use torchrun, you can just do:
`CUDA_VISIBLE_DEVICES=0 python tools/relation_train_net.py --task sgcls --save-best --config-file "configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 12 TEST.IMS _PER_BATCH 2 DTYPE "float16" SOLVER.MAX_EPOCH 20 MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR ./checkpoints/motif-precl s-exmp`

**Comment by fullsunhcc** [comment]
I have question about deactivate its usage with `TEST.INFORMATIVE False` in your training command (or config file).

I added `TEST.INFORMATIVE False` on the configs file that I will use on the training 
`configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml` 
```
TEST:
  ALLOW_LOAD_FROM_CACHE: False
  RELATION:
    SYNC_GATHER: True      # turn on will slow down the evaluation to solve the sgdet test out of memory problem
    REQUIRE_OVERLAP: False
    LATER_NMS_PREDICTION_THRES: 0.5
  CUSTUM_EVAL: False       # eval SGDet model on custum images, output a json
  CUSTUM_PATH: '.'         # the folder that contains the custum images, only jpg files are allowed  
  INFORMATIVE: False      
```
On `'config/defaults.py'` 501 line I checked it set as you mentioned (don't change anything)
```
_C.TEST.INFORMATIVE = False`
```
For the training command on one GPU I add the ' TEST.INFORMATIVE False':
`CUDA_VISIBLE_DEVICES=0 python tools/relation_train_net.py --task sgcls --save-best --config-file "configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 12 TEST.IMS_PER_BATCH 1 DTYPE "float16" SOLVER.MAX_EPOCH 20 MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR ./checkpoints/motif-precls-exmp TEST.INFORMATIVE False`

However it still gives me an this error message
`FileNotFoundError: [Errno 2] No such file or directory: '/home/uhcc/Desktop/SGG-Benchmark/datasets/vg/informative_sg.json'`

So, I made dummy files and named it 'informative_sg.json' .
However I got this error message. I think on training it is using informative_sg.json file. 
```
(scene_graph_benchmark) uhcc@uhcc-MS-7E01:~/Desktop/SGG-Benchmark$ CUDA_VISIBLE_DEVICES=0 python tools/relation_train_net.py --task sgcls --save-best --config-file "configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 12 TEST.IMS_PER_BATCH 1 DTYPE "float16" SOLVER.MAX_EPOCH 20 MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR ./checkpoints/motif-precls-exmp TEST.INFORMATIVE False
2024-07-11 15:58:29.256 | INFO     | sgg_benchmark.utils.logger:setup_logger:31 - Using loguru logger with level: INFO
2024-07-11 15:58:29.256 | INFO     | __main__:main:444 - Using 1 GPUs
2024-07-11 15:58:29.256 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 1: Collecting environment info... ####################
2024-07-11 15:58:30.423 | INFO     | __main__:main:457 - Saving config into: ./checkpoints/motif-precls-exmp/config.yml
2024-07-11 15:58:30.427 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 2: Building model... ####################
2024-07-11 15:58:31.569 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-07-11 15:58:31.569 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-07-11 15:58:31.569 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./checkpoints/motif-precls-exmp/VG150_train_statistics.cache
2024-07-11 15:58:31.569 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
2024-07-11 15:58:32.442 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-07-11 15:58:32.442 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-07-11 15:58:32.443 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./checkpoints/motif-precls-exmp/VG150_train_statistics.cache
2024-07-11 15:58:32.443 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
2024-07-11 15:58:36.981 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 3: Building optimizer and scheduler... ####################
2024-07-11 15:58:36.982 | INFO     | sgg_benchmark.utils.checkpoint:load:65 - Loading checkpoint from ./checkpoints/pretrained_faster_rcnn/model_final.pth
2024-07-11 15:58:37.400 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 4: Building checkpointer ####################
2024-07-11 15:58:38.155 | INFO     | sgg_benchmark.utils.miscellaneous:save_labels:50 - Saving labels mapping into ./checkpoints/motif-precls-exmp/labels.json
2024-07-11 15:58:38.493 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 5: Building dataloader ####################
2024-07-11 15:58:38.493 | INFO     | __main__:train:203 - Validate before training
2024-07-11 15:58:38.496 | INFO     | sgg_benchmark.engine.inference:inference:163 - Start evaluation on VG150_val dataset(5000 images).
  0%|                                                                                                                                            | 0/5000 [00:00<?, ?it/s]/home/uhcc/anaconda3/envs/scene_graph_benchmark/lib/python3.11/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1708025842427/work/aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [04:15<00:00, 19.55it/s]
2024-07-11 16:02:54.319 | INFO     | sgg_benchmark.engine.inference:inference:181 - Total run time: 0:04:15.823242 (0.05116464848518371 s / img per device, on 1 devices)
2024-07-11 16:02:54.319 | INFO     | sgg_benchmark.engine.inference:inference:190 - Average latency per image: 50.106024130249025ms
2024-07-11 16:02:54.319 | INFO     | sgg_benchmark.engine.inference:inference:193 - Standard deviation of latency: 8.518258954048756ms
Traceback (most recent call last):
  File "/home/uhcc/Desktop/SGG-Benchmark/tools/relation_train_net.py", line 491, in <module>
    main()
  File "/home/uhcc/Desktop/SGG-Benchmark/tools/relation_train_net.py", line 470, in main
    model, best_checkpoint = train(
                             ^^^^^^
  File "/home/uhcc/Desktop/SGG-Benchmark/tools/relation_train_net.py", line 204, in train
    run_val(cfg, model, val_data_loaders, args['distributed'], logger, device=device)
  File "/home/uhcc/Desktop/SGG-Benchmark/tools/relation_train_net.py", line 323, in run_val
    dataset_result = inference(
                     ^^^^^^^^^^
  File "/home/uhcc/Desktop/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 222, in inference
    return evaluate(cfg=cfg,
           ^^^^^^^^^^^^^^^^^
  File "/home/uhcc/Desktop/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate
    return vg_evaluation(**args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uhcc/Desktop/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/__init__.py", line 15, in vg_evaluation
    return do_vg_evaluation(
           ^^^^^^^^^^^^^^^^^
  File "/home/uhcc/Desktop/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 56, in do_vg_evaluation
    gt = dataset.get_groundtruth(image_id, evaluation=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uhcc/Desktop/SGG-Benchmark/sgg_benchmark/data/datasets/visual_genome.py", line 241, in get_groundtruth
    target.add_field("informative_rels", self.informative_graphs[str(img_info['image_id'])])
                                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '1'
```

How can I handle this issue? I would really appreciate your help.

Thank you.

**Comment by Maelic** [comment]
Did you download the visual genome dataset correctly? If the informative_sg.json file is not found, the informative_graphs dict should be populated with the correct image ids anyway, see:
[https://github.com/Maelic/SGG-Benchmark/blob/647e995caaec734d0df55af4c841960e2b415833/sgg_benchmark/data/datasets/visual_genome.py#L80](https://github.com/Maelic/SGG-Benchmark/blob/647e995caaec734d0df55af4c841960e2b415833/sgg_benchmark/data/datasets/visual_genome.py#L80)

But this requires the image_info to be correct, if you didn't download all the images you may encountered this issue because the `load_image_filenames` function will not return anything in `self.img_info`

**Comment by fullsunhcc** [comment]
Thank you for your quick reply.
I downloaded the data several times and checked that it is correctly unzipped. 
The error was not caused by the dataset; the reason for the error is that I am working on VS Code, not Jupyter. 
So, I changed the code in `visual_genome.py` from line 77 to line 80 to this form:
```
if informative_file is not None:
    with open(informative_file, 'r') as f:
        self.informative_graphs = json.load(f)
else:
    self.informative_graphs = {str(img['image_id']): [] for img in self.img_info}
```
After changing the code, it fixed the above issue!

However, my training stops at 5 epochs due to early stopping. 
The results look like this. Is this good enough for Detection evaluation mAp and scene graph detection? 
Compared to the MODEL_ZOO.md, it has too low value...
Do you think I failed the training?

```
2024-07-14 19:38:06.644 | INFO     | __main__:train:242 - Average validation Result for mR: 0.1000
2024-07-14 19:38:06.647 | INFO     | sgg_benchmark.utils.checkpoint:save:53 - Saving checkpoint to ./checkpoints/motif-precls-exmp/best_model_epoch_4.pth
2024-07-14 19:38:08.515 | INFO     | __main__:train:255 - New best model saved at iteration 4
2024-07-14 19:38:08.516 | INFO     | __main__:train:257 - Now best epoch in mR@k is : 4, with value is 0.09997132150367383
2024-07-14 19:38:08.516 | INFO     | sgg_benchmark.solver.lr_scheduler:step:176 - Trigger Schedule Decay, RL has been reduced by factor 0.1
Epoch=5 | Loss=0.49 | Mem=6014.66MB: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 4812/4812 [40:59<00:00,  1.96it/s]
2024-07-14 20:19:08.002 | INFO     | __main__:train:227 - Epoch 5 training time: 2459.49 s
2024-07-14 20:19:08.005 | INFO     | __main__:train:234 - Start validating
2024-07-14 20:19:08.038 | INFO     | sgg_benchmark.engine.inference:inference:163 - Start evaluation on VG150_val dataset(5000 images).
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [04:15<00:00, 19.58it/s]
2024-07-14 20:23:23.351 | INFO     | sgg_benchmark.engine.inference:inference:181 - Total run time: 0:04:15.312531 (0.05106250610351563 s / img per device, on 1 devices)
2024-07-14 20:23:23.351 | INFO     | sgg_benchmark.engine.inference:inference:190 - Average latency per image: 49.81410228500366ms
2024-07-14 20:23:23.351 | INFO     | sgg_benchmark.engine.inference:inference:193 - Standard deviation of latency: 7.4451654776503ms
creating index...
index created!
Loading and preparing results...
Converting ndarray to lists...
(62754, 7)
0/62754
DONE (t=0.23s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=9.11s).
Accumulating evaluation results...
DONE (t=1.17s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.584
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.601
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.595
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.393
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.538
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.610
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.443
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.654
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.658
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.444
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.608
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.676
2024-07-14 20:23:55.464 | INFO     | sgg_benchmark.data.datasets.evaluation.vg.vg_eval:do_vg_evaluation:224 - 
====================================================================================================
Detection evaluation mAp=0.6006
====================================================================================================
SGG eval:     R @ 20: 0.3785;     R @ 50: 0.4114;     R @ 100: 0.4204;  for mode=sgcls, type=Recall(Main).
SGG eval:  ng-R @ 20: 0.4300;  ng-R @ 50: 0.5093;  ng-R @ 100: 0.5496;  for mode=sgcls, type=No Graph Constraint Recall(Main).
SGG eval:    zR @ 20: 0.0674;    zR @ 50: 0.1022;    zR @ 100: 0.1044;  for mode=sgcls, type=Zero Shot Recall.
SGG eval: ng-zR @ 20: 0.0741; ng-zR @ 50: 0.1511; ng-zR @ 100: 0.2089;  for mode=sgcls, type=No Graph Constraint Zero Shot Recall.
SGG eval:    mR @ 20: 0.0918;    mR @ 50: 0.1058;    mR @ 100: 0.1104;  for mode=sgcls, type=Mean Recall.
----------------------- Details ------------------------
(above:0.1370) (across:0.0000) (against:0.0000) (along:0.0449) (and:0.0000) (at:0.1416) (attached to:0.0000) (behind:0.2727) (belonging to:0.0000) (between:0.0000) (carrying:0.2719) (covered in:0.0357) (covering:0.0122) (eating:0.4048) (flying in:0.0000) (for:0.0741) (from:0.0000) (growing on:0.0000) (hanging from:0.0000) (has:0.5027) (holding:0.2782) (in:0.2022) (in front of:0.1449) (laying on:0.0476) (looking at:0.0000) (lying on:0.0000) (made of:0.0000) (mounted on:0.0000) (near:0.3114) (of:0.2971) (on:0.5557) (on back of:0.0000) (over:0.0549) (painted on:0.0000) (parked on:0.0273) (part of:0.0000) (playing:0.0000) (riding:0.2307) (says:0.0000) (sitting on:0.1583) (standing on:0.0065) (to:0.0556) (under:0.1539) (using:0.1538) (walking in:0.0000) (walking on:0.1774) (watching:0.1667) (wearing:0.5150) (wears:0.0000) (with:0.0850) 
--------------------------------------------------------
SGG eval: ng-mR @ 20: 0.1416; ng-mR @ 50: 0.2166; ng-mR @ 100: 0.2843;  for mode=sgcls, type=No Graph Constraint Mean Recall.
----------------------- Details ------------------------
(above:0.4774) (across:0.0556) (against:0.0000) (along:0.4808) (and:0.1290) (at:0.4753) (attached to:0.1843) (behind:0.3644) (belonging to:0.2143) (between:0.1154) (carrying:0.4298) (covered in:0.2857) (covering:0.2514) (eating:0.5476) (flying in:0.0000) (for:0.1667) (from:0.0000) (growing on:0.1333) (hanging from:0.5478) (has:0.5618) (holding:0.4014) (in:0.4545) (in front of:0.4118) (laying on:0.2381) (looking at:0.2609) (lying on:0.3111) (made of:0.0000) (mounted on:0.0000) (near:0.4427) (of:0.5661) (on:0.6087) (on back of:0.0455) (over:0.2104) (painted on:0.1429) (parked on:0.6843) (part of:0.0833) (playing:0.0000) (riding:0.4658) (says:0.0000) (sitting on:0.3787) (standing on:0.2018) (to:0.1667) (under:0.3019) (using:0.3077) (walking in:0.1538) (walking on:0.3083) (watching:0.2353) (wearing:0.5239) (wears:0.4885) (with:0.4027) 
--------------------------------------------------------
SGG eval:     F1 @ 20: 0.1477;     F1 @ 50: 0.1684;     F1 @ 100: 0.1749;  for mode=sgcls, type=F1.
SGG eval:     A @ 20: 0.4408;     A @ 50: 0.4432;     A @ 100: 0.4432;  for mode=sgcls, type=TopK Accuracy.
====================================================================================================
```

**Comment by Maelic** [comment]
Hi @fullsunhcc, great to hear that you fixed your problem (even though the fix seems very weird to me, I am also using VS code and everything works fine for me).

Regarding your results, it is hard for me to comment on them without your config file and settings, a lot of parameters can influence performance such as batch size or learning rate. You can try to do some hyperparameter tuning using [my script with Raytune](https://github.com/Maelic/SGG-Benchmark/tree/647e995caaec734d0df55af4c841960e2b415833?tab=readme-ov-file#hyperparameters-tuning) if you want to optimize your training.
I have also to say that the YOLOV8 weights that I trained (the yolov8m_vg150.pt checkpoint) are not very good for VG150 because of the strong annotations biases of VG150, which can lead to worse performance than the baseline with Faster-RCNN. You could try another version of yolov8 such as L or X or even YOLOV10 to get better performance. You can find a script to generate yolo-type annotations for VG150 [here](https://github.com/Maelic/SGG-Benchmark/blob/647e995caaec734d0df55af4c841960e2b415833/process_data/convert_to_yolo.ipynb).

Finally, I don't know what is your use case but I would heavily recommend you to train and compare on the PSG or IndoorVG datasets instead of VG150. VG150 is very noisy and almost useless at this point.

**Comment by fullsunhcc** [comment]
Thank you!

Upon rechecking, I have not changed the config file and settings that were downloaded from GitHub. I will try some of the hyperparameter adjustments you recommended. Additionally, I will attempt to train on the PSG or IndoorVG dataset.

Thank you very much for your quick reply and kindness.
