### ISSUE TITLE
Issue with install the lib

### ISSUE THREAD

**Issue by Ali-Hatami** [Maelic/SGG-Benchmark#2]
Hi,

I've managed to resolve some issues with installing requirements. However, I'm encountering a problem while installing the library (python setup.py build develop). It's showing the error message below, and I'm unsure how to resolve it. Any help would be appreciated.

Traceback (most recent call last):
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    setup(
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/alihat/miniconda3/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by Ali-Hatami** [comment]
I am using torch=1.11.0+cu115 and torchvision=0.12.0+cu115. I do not have access to change the CUDA version.

**Comment by Maelic** [comment]
Hum I didn't test with this specific version of torch but I was using torch 1.12 before with cuda 11.7 and it was working fine, try to update to the latest version of torch you can with your cuda requirements maybe.

I am trying to remove all dependencies on compiled cuda code and replace it with alternatives from torchvision, I don't know when I will be done with that exactly but if I succeed you would be able to use the codebase without compiling anything.
N.b. Basically, the problem is that the cuda code in [csrc](https://github.com/Maelic/SGG-Benchmark/tree/main/sgg_benchmark/csrc) comes from an old implementation in the original detectron codebase but now most of the functions there have their own implementation in torchvision (such as ROIAlign).

**Comment by Maelic** [comment]
Closing due to inactivity.
