### ISSUE TITLE
Issues with the dataset during training.

### ISSUE THREAD

**Issue by Young-Loser** [Maelic/SGG-Benchmark#34]
I found that the potential cause of the KeyError might be the lack of corresponding data for certain image IDs in self.informative_graphs.
<img width="436" alt="1728716051772" src="https://github.com/user-attachments/assets/3d31609d-2df6-46e8-9169-c19884149208">
In the get_groundtruth function, self.informative_graphs is used to get the value corresponding to img_info['image_id']. If the corresponding image_id cannot be found in self.informative_graphs, a KeyError will be raised.
<img width="470" alt="1728716079037" src="https://github.com/user-attachments/assets/0f894afd-a76b-499f-abd7-89ebbefc510c">
Could you please tell me how to solve this problem? Thank you very much!!!!

**Comment by Maelic** [comment]
Hello, I just pushed a new version that should solve your problem, please update and let me know if it works.

**Comment by Young-Loser** [comment]
> Hello, I just pushed a new version that should solve your problem, please update and let me know if it works.

Thank you very much! I am trying this.

**Comment by Young-Loser** [comment]
I have tried the new version. But I have to do a little work to run the code. 
`            informative_file = ""
            
            if informative_file != "" and os.path.exists(informative_file):
                self.informative_graphs = json.load(open(informative_file, 'r'))
            else:
                self.informative_graphs = None`
But here also had a issue:
<img width="510" alt="1728999286093" src="https://github.com/user-attachments/assets/2dabf3c6-200b-4252-8a55-0998e8df3f1a">

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2024-10-15 20:58:13.674 | INFO     | sgg_benchmark.utils.logger:setup_logger:31 - Using loguru logger with level: INFO
2024-10-15 20:58:13.674 | INFO     | __main__:main:1467 - Using 2 GPUs
2024-10-15 20:58:13.674 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 1: Collecting environment info... ####################
2024-10-15 20:58:16.880 | INFO     | __main__:main:1480 - Saving config into: /Dpan/wyc/realtime_rwsg/MODELSAVE/config.yml
2024-10-15 20:58:16.900 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 2: Building model... ####################
Overriding model.yaml nc=80 with nc=150
2024-10-15 20:58:17.806 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-10-15 20:58:17.806 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-10-15 20:58:17.806 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: /Dpan/wyc/realtime_rwsg/MODELSAVE/VG150_train_statistics.cache
2024-10-15 20:58:17.807 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
2024-10-15 20:58:20.470 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-10-15 20:58:20.471 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-10-15 20:58:20.471 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: /Dpan/wyc/realtime_rwsg/MODELSAVE/VG150_train_statistics.cache
2024-10-15 20:58:20.472 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
loading word vectors from ./glove.6B.200d.pt
loading word vectors from ./glove.6B.200d.pt
2024-10-15 20:58:24.398 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 3: Building optimizer and scheduler... ####################
Transferred 439/511 items from pretrained weights
2024-10-15 20:58:24.566 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 4: Loading Backbone weights from /Dpan/wyc/realtime_rwsg/PREMODEL/yolov8m_vg150.pt ####################
2024-10-15 20:58:24.567 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 5: Building checkpointer ####################
2024-10-15 20:58:27.187 | INFO     | sgg_benchmark.utils.miscellaneous:save_labels:50 - Saving labels mapping into /Dpan/wyc/realtime_rwsg/MODELSAVE/labels.json
  0%|                                                                                                                                                                            | 1/4812 [00:00<23:58,  3.34it/s]2024-10-15 20:58:28.179 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 6: Building dataloader ####################
2024-10-15 20:58:28.179 | INFO     | __main__:train:1224 - Start training for 20 epochs
Epoch=0 | Loss=0.07 | Mem=2237.81MB: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4812/4812 [21:37<00:00,  3.71it/s]
Epoch=0 | Loss=0.11 | Mem=2349.30MB: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4812/4812 [21:36<00:00,  3.71it/s]
2024-10-15 21:20:04.903 | INFO     | __main__:train:1244 - Epoch 0 training time: 1296.72 s
2024-10-15 21:20:04.904 | INFO     | __main__:train:1251 - Start validating
2024-10-15 21:20:04.925 | INFO     | sgg_benchmark.engine.inference:inference:263 - Start evaluation on VG150_val dataset(5000 images).
  0%|                                                                                                                                                                                    | 0/2500 [00:00<?, ?it/s]/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/utils/comm.py:65: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.ByteStorage.from_buffer(buffer)
/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/utils/comm.py:65: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.ByteStorage.from_buffer(buffer)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2500/2500 [05:26<00:00,  7.66it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2500/2500 [05:26<00:00,  7.66it/s]
2024-10-15 21:25:31.257 | INFO     | sgg_benchmark.engine.inference:inference:280 - Total run time: 0:04:47 (57.50201838989258 ms / img per device, on 2 devices)
2024-10-15 21:25:31.259 | INFO     | sgg_benchmark.engine.inference:inference:289 - Average latency per image: 57.50201838989258ms
2024-10-15 21:25:31.259 | INFO     | sgg_benchmark.engine.inference:inference:292 - Standard deviation of latency: 15.11866069945474ms
2024-10-15 21:25:33.211 | INFO     | sgg_benchmark.data.datasets.evaluation.vg.vg_eval:do_vg_evaluation:70 - Dataset does not have informative_rels, skipping informative evaluation for dataset: VG150
creating index...
index created!
Loading and preparing results...
Converting ndarray to lists...
(0, 7)
Traceback (most recent call last):
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1514, in <module>
    main()
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1493, in main
    model, best_checkpoint = train(
                             ^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1253, in train
    val_result = run_val(cfg, model, val_data_loaders, args['distributed'], logger)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1343, in run_val
    dataset_result = inference(
                     ^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 335, in inference
    return evaluate(cfg=cfg,
           ^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate
    return vg_evaluation(**args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/__init__.py", line 15, in vg_evaluation
    return do_vg_evaluation(
           ^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 119, in do_vg_evaluation
    res = fauxcoco.loadRes(cocolike_predictions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/pycocotools/coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
                    ~~~~^^^
IndexError: list index out of range
[2024-10-15 21:25:38,539] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1038139 closing signal SIGTERM
[2024-10-15 21:25:38,904] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1038138) of binary: /Dpan/wyc/anaconda3/envs/rtrw_sg/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/anaconda3/envs/rtrw_sg/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/relation_train_net.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-15_21:25:38
  host      : server-Super-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1038138)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
