### ISSUE TITLE
Unable to get prediction results in coco with yolov8m

### ISSUE THREAD

**Issue by Mingyuan1997** [Maelic/SGG-Benchmark#35]
Thanks for the great work and a quick fix on the informative file!

However I still got into trouble when I tried running the training command. Could you help me to see why I cannot get prediction results from the detector?

_I used pretrained weight in your link (yolov8 trained at VG)_

**CUDA_VISIBLE_DEVICES=0 python tools/relation_train_net.py --task sgdet --save-best --config-file "configs/VG150/e2e_relation_yolov8m.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE none MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs SOLVER.IMS_PER_BATCH 12 TEST.IMS_PER_BATCH 2 DTYPE "float16" SOLVER.MAX_EPOCH 20 MODEL.PRETRAINED_DETECTOR_CKPT ./yolov8m_vg150.pt OUTPUT_DIR ./checkpoints/**

2024-10-14 22:40:25.637 | INFO     | sgg_benchmark.utils.logger:setup_logger:31 - Using loguru logger with level: INFO
2024-10-14 22:40:25.638 | INFO     | __main__:main:444 - Using 1 GPUs
2024-10-14 22:40:25.638 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 1: Collecting environment info... ####################
2024-10-14 22:40:29.360 | INFO     | __main__:main:457 - Saving config into: ./checkpoints/config.yml
2024-10-14 22:40:29.377 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 2: Building model... ####################
Overriding model.yaml nc=80 with nc=150
2024-10-14 22:40:30.206 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-10-14 22:40:30.206 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-10-14 22:40:30.206 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./checkpoints/VG150_train_statistics.cache
2024-10-14 22:40:30.206 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
2024-10-14 22:40:34.091 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-10-14 22:40:34.091 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-10-14 22:40:34.092 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./checkpoints/VG150_train_statistics.cache
2024-10-14 22:40:34.092 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
loading word vectors from ./glove.6B.200d.pt
2024-10-14 22:40:39.691 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 3: Building optimizer and scheduler... ####################
Transferred 439/511 items from pretrained weights
2024-10-14 22:40:39.838 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 4: Loading Backbone weights from ./yolov8m_vg150.pt ####################
2024-10-14 22:40:39.839 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 5: Building checkpointer ####################
108073
/home/haozhen/mingyuan/SGG-Benchmark/datasets/vg/VG_100K
2024-10-14 22:40:42.501 | INFO     | sgg_benchmark.utils.miscellaneous:save_labels:50 - Saving labels mapping into ./checkpoints/labels.json
108073
/home/haozhen/mingyuan/SGG-Benchmark/datasets/vg/VG_100K
2024-10-14 22:40:43.736 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 6: Building dataloader ####################
2024-10-14 22:40:43.736 | INFO     | __main__:train:203 - Validate before training
2024-10-14 22:40:43.737 | INFO     | sgg_benchmark.engine.inference:inference:263 - Start evaluation on VG150_val dataset(5000 images).
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2501/2501 [02:26<00:00, 17.07it/s]
2024-10-14 22:43:10.251 | INFO     | sgg_benchmark.engine.inference:inference:280 - Total run time: 0:02:18 (27.661574461897676 ms / img per device, on 1 devices)
2024-10-14 22:43:10.252 | INFO     | sgg_benchmark.engine.inference:inference:289 - Average latency per image: 27.661574461897676ms
2024-10-14 22:43:10.252 | INFO     | sgg_benchmark.engine.inference:inference:292 - Standard deviation of latency: 24.626527727053297ms
2024-10-14 22:43:11.539 | INFO     | sgg_benchmark.data.datasets.evaluation.vg.vg_eval:do_vg_evaluation:70 - Dataset does not have informative_rels, skipping informative evaluation for dataset: VG150
creating index...
index created!
Loading and preparing results...
Converting ndarray to lists...
(0, 7)
Traceback (most recent call last):
  File "/home/haozhen/mingyuan/SGG-Benchmark/tools/relation_train_net.py", line 491, in <module>
    main()
  File "/home/haozhen/mingyuan/SGG-Benchmark/tools/relation_train_net.py", line 470, in main
    model, best_checkpoint = train(
                             ^^^^^^
  File "/home/haozhen/mingyuan/SGG-Benchmark/tools/relation_train_net.py", line 204, in train
    run_val(cfg, model, val_data_loaders, args['distributed'], logger, device=device)
  File "/home/haozhen/mingyuan/SGG-Benchmark/tools/relation_train_net.py", line 323, in run_val
    dataset_result = inference(
                     ^^^^^^^^^^
  File "/home/haozhen/mingyuan/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 335, in inference
    return evaluate(cfg=cfg,
           ^^^^^^^^^^^^^^^^^
  File "/home/haozhen/mingyuan/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate
    return vg_evaluation(**args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/haozhen/mingyuan/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/__init__.py", line 15, in vg_evaluation
    return do_vg_evaluation(
           ^^^^^^^^^^^^^^^^^
  File "/home/haozhen/mingyuan/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 119, in do_vg_evaluation
    res = fauxcoco.loadRes(cocolike_predictions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/conda/env/scene_graph_benchmark/lib/python3.11/site-packages/pycocotools/coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
                    ~~~~^^^
IndexError: list index out of range

**Comment by Young-Loser** [comment]
I also meet this error.

**Comment by Maelic** [comment]
It seems that the object detector is not detecting anything, I will investigate this issue.

**Comment by Maelic** [comment]
I am not able to reproduce the error, can you share your config file please?

**Comment by Maelic** [comment]
You can copy the content of the .yaml file here

**Comment by Young-Loser** [comment]
> 您可以在此处复制 .yaml 文件的内容

This is my config.yml file, but I don't know why the PATHS_DATA path is like this. I have already changed the data loading path in paths_catalog.py, and I am using the VG150 dataset.
`DATALOADER:
  ASPECT_RATIO_GROUPING: true
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
DATASETS:
  NAME: ''
  TEST:
  - VG150_test
  TO_TEST: ''
  TRAIN:
  - VG150_train
  VAL:
  - VG150_val
DETECTED_SGG_DIR: .
DTYPE: float16
GLOVE_DIR: .
INPUT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  FLIP_PROB_TRAIN: 0.5
  HUE: 0.0
  MAX_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 640
  MIN_SIZE_TRAIN: 640
  PADDING: true
  PIXEL_MEAN:
  - 102.9801
  - 115.9465
  - 122.7717
  PIXEL_STD:
  - 1.0
  - 1.0
  - 1.0
  SATURATION: 0.0
  TO_BGR255: true
  VERTICAL_FLIP_PROB_TRAIN: 0.0
METRIC_TO_TRACK: mR
MODEL:
  ATTRIBUTE_ON: false
  BACKBONE:
    EXTRA_CONFIG: ''
    FREEZE: true
    FREEZE_CONV_BODY_AT: 2
    NMS_THRESH: 0.001
    TYPE: yolov8
  BOX_HEAD: false
  CLS_AGNOSTIC_BBOX_REG: false
  DEVICE: cuda
  FBNET:
    ARCH: default
    ARCH_DEF: ''
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: true
    DW_CONV_SKIP_RELU: true
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE: ''
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FLIP_AUG: false
  FPN:
    USE_GN: false
    USE_RELU: false
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1.0e-05
    NUM_GROUPS: 32
  MASK_ON: false
  META_ARCHITECTURE: GeneralizedYOLO
  PRETRAINED_DETECTOR_CKPT: /Dpan/wyc/realtime_rwsg/PREMODEL/yolov8m_vg150.pt
  RELATION_ON: true
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 1
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN:
    - false
    - false
    - false
    - false
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: true
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 64
    WITH_MODULATED_DCN: false
  ROI_ATTRIBUTE_HEAD:
    ATTRIBUTE_BGFG_RATIO: 3
    ATTRIBUTE_BGFG_SAMPLE: true
    ATTRIBUTE_LOSS_WEIGHT: 0.1
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MAX_ATTRIBUTES: 10
    NUM_ATTRIBUTES: 201
    POS_WEIGHT: 5.0
    PREDICTOR: FPNPredictor
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_BINARY_LOSS: true
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: YOLOV8FeatureExtractor
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 151
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES:
    - 0.125
    - 0.0625
    - 0.03125
    PREDICTOR: FastRCNNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    BG_IOU_THRESHOLD: 0.1
    DETECTIONS_PER_IMG: 80
    FG_IOU_THRESHOLD: 0.3
    NMS: 0.2
    NMS_FILTER_DUPLICATES: true
    POSITIVE_FRACTION: 0.5
    POST_NMS_PER_CLS_TOPN: 300
    SCORE_THRESH: 0.01
  ROI_MASK_HEAD:
    CONV_LAYERS:
    - 256
    - 256
    - 256
    - 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES:
    - 0.0625
    POSTPROCESS_MASKS: false
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_GN: false
  ROI_RELATION_HEAD:
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: true
    BATCH_SIZE_PER_IMAGE: 256
    CAUSAL:
      CONTEXT_LAYER: motifs
      EFFECT_ANALYSIS: true
      EFFECT_TYPE: TDE
      FUSION_TYPE: sum
      SEPARATE_SPATIAL: false
      SPATIAL_FOR_VISION: false
    CLASSIFIER: linear
    CONTEXT_DROPOUT_RATE: 0.2
    CONTEXT_HIDDEN_DIM: 512
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_POOLING_DIM: 2048
    CONTEXT_REL_LAYER: 1
    EMBED_DIM: 200
    FEATURE_EXTRACTOR: RelationFeatureExtractor
    LABEL_SMOOTHING_LOSS: false
    LOGIT_ADJUSTMENT: false
    LOGIT_ADJUSTMENT_TAU: 0.3
    LOSS: CrossEntropyLoss
    MLP_HEAD_DIM: 2048
    NUM_CLASSES: 51
    NUM_SAMPLE_PER_GT_REL: 4
    POOLING_ALL_LEVELS: true
    POSITIVE_FRACTION: 0.25
    PREDICTOR: MotifPredictor
    PREDICT_USE_VISION: false
    REQUIRE_BOX_OVERLAP: false
    SQUAT_MODULE:
      BETA: 0.7
      NUM_DECODER: 3
      PRETRAIN_MASK: false
      PRETRAIN_MASK_EPOCH: 1
      PRE_NORM: false
      RHO: 0.35
    TEXTUAL_FEATURES_ONLY: false
    TRANSFORMER:
      DROPOUT_RATE: 0.1
      INNER_DIM: 2048
      KEY_DIM: 64
      NUM_HEAD: 8
      OBJ_LAYER: 4
      REL_LAYER: 2
      VAL_DIM: 64
    USE_FREQUENCY_BIAS: false
    USE_GT_BOX: false
    USE_GT_OBJECT_LABEL: false
    USE_SPATIAL_FEATURES: true
    USE_UNION_FEATURES: true
    VISUAL_FEATURES_ONLY: false
  RPN:
    ANCHOR_SIZES:
    - 32
    - 64
    - 128
    - 256
    - 512
    ANCHOR_STRIDE:
    - 16
    ASPECT_RATIOS:
    - 0.5
    - 1.0
    - 2.0
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: true
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
    RPN_HEAD: SingleConvRPNHead
    RPN_MID_CHANNEL: 512
    STRADDLE_THRESH: 0
    USE_FPN: false
  RPN_ONLY: false
  TEXT_EMBEDDING: glove.6B
  VGG:
    VGG16_OUT_CHANNELS: 512
  WEIGHT: ''
  YOLO:
    IMG_SIZE: 640
    OUT_CHANNELS: 192
    SIZE: yolov8m
    WEIGHTS: ''
OUTPUT_DIR: /Dpan/wyc/realtime_rwsg/MODELSAVE
PATHS_CATALOG: /Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/config/paths_catalog.py
PATHS_DATA: /home/maelic/Documents/Datasets/VG/
SEED: 42
SOLVER:
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1
  CHECKPOINT_PERIOD: 2000
  CLIP_NORM: 5.0
  GAMMA: 0.5
  GRAD_NORM_CLIP: 5.0
  IMS_PER_BATCH: 12
  MAX_EPOCH: 20
  MAX_ITER: 40000
  MOMENTUM: 0.9
  OPTIMIZER: SGD
  PRE_VAL: true
  PRINT_GRAD_FREQ: 4000
  SCHEDULE:
    COOLDOWN: 0
    FACTOR: 0.1
    MAX_DECAY_STEP: 3
    PATIENCE: 2
    THRESHOLD: 0.001
    TYPE: WarmupReduceLROnPlateau
  STEPS:
  - 10000
  - 16000
  TO_VAL: true
  UPDATE_SCHEDULE_DURING_LOAD: false
  VAL_PERIOD: 2000
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  ALLOW_LOAD_FROM_CACHE: false
  BBOX_AUG:
    ENABLED: false
    H_FLIP: false
    MAX_SIZE: 4000
    SCALES: []
    SCALE_H_FLIP: false
  CUSTUM_EVAL: false
  CUSTUM_PATH: .
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 2
  INFORMATIVE: true
  RELATION:
    IOU_THRESHOLD: 0.5
    LATER_NMS_PREDICTION_THRES: 0.5
    MULTIPLE_PREDS: false
    REQUIRE_OVERLAP: true
    SYNC_GATHER: true
  SAVE_PROPOSALS: false
  TOP_K: 100
VERBOSE: INFO
`

**Comment by Mingyuan1997** [comment]
Thanks for your investigation. My yaml as follows:

INPUT:
  MIN_SIZE_TRAIN: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640
  PADDING: True
MODEL:
  TEXT_EMBEDDING: glove.6B
  META_ARCHITECTURE: "GeneralizedYOLO"
  BOX_HEAD: False
  WEIGHT: ""
  PRETRAINED_DETECTOR_CKPT: "/home/haozhen/mingyuan/SGG-Benchmark/yolov8m_vg150.pt"
  BACKBONE:
    TYPE: "yolov8"
    NMS_THRESH: 0.001
    FREEZE: True
  YOLO:
    SIZE: "yolov8m"
    OUT_CHANNELS: 192 # 192 for yolov8m, 256 for yolov8l
  RELATION_ON: True
  ATTRIBUTE_ON: False
  FLIP_AUG: False            # if there is any left-right relation, FLIP AUG should be false
  ROI_HEADS:
    POSITIVE_FRACTION: 0.5
    FG_IOU_THRESHOLD: 0.3
    BG_IOU_THRESHOLD: 0.1
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 80
    NMS_FILTER_DUPLICATES: True
    NMS: 0.2
  ROI_BOX_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125)
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "YOLOV8FeatureExtractor"
    NUM_CLASSES: 151              # 151 for VG, 1201 for GQA
  ROI_RELATION_HEAD:
    EMBED_DIM: 200
    USE_GT_BOX: False
    USE_GT_OBJECT_LABEL: False
    USE_SPATIAL_FEATURES: True
    REQUIRE_BOX_OVERLAP: False              # for sgdet, during training, only train pairs with overlap
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: True    # for sgdet only, in case some gt boxes are missing
    NUM_CLASSES: 51                 # 51 for VG, 201 for GQA (not contain "to the left of" & "to the right of")
    BATCH_SIZE_PER_IMAGE: 256      # sample as much as possible
    POSITIVE_FRACTION: 0.25
    CONTEXT_POOLING_DIM: 2048
    CONTEXT_HIDDEN_DIM: 512         #1024 for VCTree
    POOLING_ALL_LEVELS: True
    LABEL_SMOOTHING_LOSS: False
    FEATURE_EXTRACTOR: "RelationFeatureExtractor"
    #################### Select Relationship Model ####################
    #PREDICTOR: "MotifPredictor"
    #PREDICTOR: "VCTreePredictor"
    #PREDICTOR: "TransformerPredictor"
    PREDICTOR: "CausalAnalysisPredictor"
    ################# Parameters for Motif Predictor ##################
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_REL_LAYER: 1
    ############# Parameters for Causal Unbias Predictor ##############
    ### Implementation for paper "Unbiased Scene Graph Generation from Biased Training"
    CAUSAL:
      EFFECT_TYPE: 'TDE'             # candicates: 'TDE', 'NIE', 'TE', 'none'
      FUSION_TYPE: 'sum'              # candicates: 'sum', 'gate'         
      SEPARATE_SPATIAL: False         # separate spatial in union feature
      CONTEXT_LAYER: "motifs"         # candicates: motifs, vctree, vtranse
      EFFECT_ANALYSIS: True
    ############### Parameters for Transformer Predictor ##############
    TRANSFORMER:
      DROPOUT_RATE: 0.1
      OBJ_LAYER: 4
      REL_LAYER: 2
      NUM_HEAD: 8
      KEY_DIM: 64
      VAL_DIM: 64
      INNER_DIM: 2048 
DATASETS:
  TRAIN: ("VG150_train",)
  VAL: ("VG150_val",)
  TEST: ("VG150_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  MAX_EPOCH: 20
  BIAS_LR_FACTOR: 1
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 5.0
  STEPS: (10000, 16000)
  MAX_ITER: 40000
  VAL_PERIOD: 2000
  CHECKPOINT_PERIOD: 2000
  PRINT_GRAD_FREQ: 4000
  SCHEDULE:
    # the following paramters are only used for WarmupReduceLROnPlateau
    TYPE: "WarmupReduceLROnPlateau"    # WarmupMultiStepLR, WarmupReduceLROnPlateau
    PATIENCE: 2
    THRESHOLD: 0.001
    COOLDOWN: 0
    FACTOR: 0.1
    MAX_DECAY_STEP: 3
OUTPUT_DIR: '/checkpoints'
TEST:
  ALLOW_LOAD_FROM_CACHE: False
  INFORMATIVE: True
  RELATION:
    SYNC_GATHER: True      # turn on will slow down the evaluation to solve the sgdet test out of memory problem
    REQUIRE_OVERLAP: True
    LATER_NMS_PREDICTION_THRES: 0.5
  CUSTUM_EVAL: False       # eval SGDet model on custum images, output a json
  CUSTUM_PATH: '.'         # the folder that contains the custum images, only jpg files are allowed

**Comment by Maelic** [comment]
After a lot of digging I think I found out the issue, it is related to the latest ultralytics implementation. In a recent release, ultralytics changed their codebase for yolov8, and this impacted my implementation of the yolov8 backbone here. 
As a workaround for now, you can fallback to the previous version of ultralytics as follows:
```pip install ultralytics==8.2.70```
This should solve the issue. I will update the requirements accordingly.

**Comment by Young-Loser** [comment]
> 经过大量挖掘，我想我找到了问题所在，它与最新的 ultralytics 实现有关。在最近的一个版本中，ultralytics 更改了 yolov8 的代码库，这影响了我在这里对 yolov8 主干的实现。 作为一种解决方法，您可以按如下方式回退到以前版本的 ultralytics： `pip install ultralytics==8.2.70` 这应该可以解决问题。我会相应地更新要求。

I tried the methods you suggested, and the previous error is indeed gone. However, now there's a new error:
`File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1514, in <module>
    main()
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1493, in main
    model, best_checkpoint = train(
                             ^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1253, in train
    val_result = run_val(cfg, model, val_data_loaders, args['distributed'], logger)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1343, in run_val
    dataset_result = inference(
                     ^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 335, in inference
    return evaluate(cfg=cfg,
           ^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate
    return vg_evaluation(**args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/__init__.py", line 15, in vg_evaluation
    return do_vg_evaluation(
           ^^^^^^^^^^^^^^^^^
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 159, in do_vg_evaluation
    evaluate_relation_of_one_image(groundtruth, prediction, global_container, evaluator, informative=informative)
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 287, in evaluate_relation_of_one_image
    v.calculate(global_container, local_container, mode)
  File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/sgg_eval.py", line 327, in calculate
    gt_relationships = local_container['informative_rels']
                       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'informative_rels'
`

**Comment by Young-Loser** [comment]
我尝试了你建议的方法，之前的错误确实消失了。但是现在又出现了一个新的错误：
File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1514, in <module> main() File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1493, in main model, best_checkpoint = train( ^^^^^^ File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1253, in train val_result = run_val(cfg, model, val_data_loaders, args['distributed'], logger) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/tools/relation_train_net.py", line 1343, in run_val dataset_result = inference( ^^^^^^^^^^ File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 335, in inference return evaluate(cfg=cfg, ^^^^^^^^^^^^^^^^^ File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate return vg_evaluation(**args) ^^^^^^^^^^^^^^^^^^^^^ File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/__init__.py", line 15, in vg_evaluation return do_vg_evaluation( ^^^^^^^^^^^^^^^^^ File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 159, in do_vg_evaluation evaluate_relation_of_one_image(groundtruth, prediction, global_container, evaluator, informative=informative) File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 287, in evaluate_relation_of_one_image v.calculate(global_container, local_container, mode) File "/Dpan/wyc/realtime_rwsg/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/sgg_eval.py", line 327, in calculate gt_relationships = local_container['informative_rels'] ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'informative_rels'

**Comment by Mingyuan1997** [comment]
Thank you so much and I do appreciate tremendous efforts you put in investigating the issue. The detector release is always unstable lol. I have not followed the yolo line of work in recent years. Thanks again!

**Comment by Maelic** [comment]
No worries, hope it helps.
By the way, you should put ```Informative: False``` in your .yaml config files to not get bothered by the informative_rels etc @Mingyuan1997 @Young-Loser

**Comment by Young-Loser** [comment]
您好！看到您的回复，我觉得您应该是中国人。我是山东大学研一新生。我有一些关于这个项目复现的问题想向您请教，我是sgg初学者，想和您进行交流。我的邮箱是[1339241893@qq.com](mailto:1339241893@qq.com)，我的微信是：XC-992997，希望与您加上好友进行交流。期待得到您的回复，希望与您进行交流学习！（如果可以的话，您可以回复我您的微信，我来加您）
