### ISSUE TITLE
Can't train a sgdet modell Key Error 

### ISSUE THREAD

**Issue by Koralion** [Maelic/SGG-Benchmark#4]
`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 10025 --nproc_per_node=1 tools/relation_train_net.py --task sgdet --save-best --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.PREDICTOR MotifPredictor SOLVER.IMS_PER_BATCH 12 TEST.IMS_PER_BATCH 1 DTYPE "float16" SOLVER.MAX_ITER 50000 SOLVER.VAL_PERIOD 2000 SOLVER.CHECKPOINT_PERIOD 2000 MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/upload_causal_motif_sgdet/model_0028000.pth OUTPUT_DIR ./checkpoints/sgdet_causal_motif_base
/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
2024-04-19 14:51:57.920 | INFO     | sgg_benchmark.utils.logger:setup_logger:30 - Using loguru logger with level: INFO
2024-04-19 14:51:57.920 | INFO     | __main__:main:428 - Using 1 GPUs
2024-04-19 14:51:57.920 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 1: Collecting environment info... ####################
2024-04-19 14:51:59.568 | INFO     | __main__:main:441 - Saving config into: ./checkpoints/sgdet_causal_motif_base/config.yml
2024-04-19 14:51:59.576 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 2: Building model... ####################
2024-04-19 14:52:01.926 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-04-19 14:52:01.926 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-04-19 14:52:01.927 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:46 - Unable to load data statistics from: ./checkpoints/sgdet_causal_motif_base/VG_stanford_filtered_with_attribute_train_statistics.cache
100%|██████████████████████████████████| 56224/56224 [00:04<00:00, 11753.31it/s]
2024-04-19 14:52:18.850 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:70 - Save data statistics to: ./checkpoints/sgdet_causal_motif_base/VG_stanford_filtered_with_attribute_train_statistics.cache
2024-04-19 14:52:18.851 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:71 - ----------------------------------------------------------------------------------------------------
2024-04-19 14:52:24.311 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-04-19 14:52:24.311 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-04-19 14:52:24.311 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./checkpoints/sgdet_causal_motif_base/VG_stanford_filtered_with_attribute_train_statistics.cache
2024-04-19 14:52:24.311 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
loading word vectors from ./glove.6B.200d.pt
loading word vectors from ./glove.6B.200d.pt
2024-04-19 14:52:27.012 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 3: Building optimizer and scheduler... ####################
2024-04-19 14:52:27.013 | INFO     | sgg_benchmark.utils.checkpoint:load:65 - Loading checkpoint from ./checkpoints/upload_causal_motif_sgdet/model_0028000.pth
2024-04-19 14:52:31.437 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 4: Building checkpointer ####################
2024-04-19 14:52:33.093 | INFO     | sgg_benchmark.utils.miscellaneous:save_labels:41 - Saving labels mapping into ./checkpoints/sgdet_causal_motif_base/labels.json
2024-04-19 14:52:33.755 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 5: Building dataloader ####################
2024-04-19 14:52:33.756 | INFO     | __main__:train:193 - Validate before training
2024-04-19 14:52:33.758 | INFO     | sgg_benchmark.engine.inference:inference:152 - Start evaluation on VG_stanford_filtered_with_attribute_val dataset(5000 images).
  0%|                                                  | 0/5000 [00:00<?, ?it/s]/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1708025845868/work/aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|███████████████████████████████████████| 5000/5000 [24:08<00:00,  3.45it/s]
2024-04-19 15:16:42.741 | INFO     | sgg_benchmark.engine.inference:inference:170 - Total run time: 0:24:08.982855 (0.2897965710163116 s / img per device, on 1 devices)
2024-04-19 15:16:42.741 | INFO     | sgg_benchmark.engine.inference:inference:176 - Model inference time: 0:23:56.858004 (0.28737160081863405 s / img per device, on 1 devices)
Traceback (most recent call last):
  File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 474, in <module>
    main()
  File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 453, in main
    model, best_checkpoint = train(
                             ^^^^^^
  File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 194, in train
    run_val(cfg, model, val_data_loaders, args['distributed'], logger, device=device)
  File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 309, in run_val
    dataset_result = inference(
                     ^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 212, in inference
    return evaluate(cfg=cfg,
           ^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/__init__.py", line 27, in evaluate
    return vg_evaluation(**args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/__init__.py", line 15, in vg_evaluation
    return do_vg_evaluation(
           ^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/sgg_benchmark/data/datasets/evaluation/vg/vg_eval.py", line 59, in do_vg_evaluation
    gt = dataset.get_groundtruth(image_id, evaluation=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/sgg_benchmark/data/datasets/visual_genome.py", line 236, in get_groundtruth
    target.add_field("informative_rels", self.informative_graphs[str(img_info['image_id'])])
                                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '1'
[2024-04-19 15:16:45,643] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 34995) of binary: /home/adrian/.conda/envs/sgg_benchmark/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launch.py", line 198, in <module>
    main()
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launch.py", line 194, in main
    launch(args)
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launch.py", line 179, in launch
    run(args)
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/relation_train_net.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-19_15:16:45
  host      : adrian-tower
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 34995)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`

Hey and thank you for updating the codebase, sadly i can't train a sgdet model maybe you could help me with this key error?

I modified the paths and used your zeroshot.pytorch file with your config.file

i also wasn't able to use the demo you created with the pretrained model from the original causal_motif_sgdet, there i had another problem with this error

`
RuntimeError: Given groups=1, weight of size [256, 256, 3, 3], expected input[1, 1024, 38, 38] to have 256 channels, but got 1024 channels instead
`

**Comment by Maelic** [comment]
You need to deactivate the informative evaluation with TEST.INFORMATIVE: False in your config file and it should work.

Your error for the demo is a bit weirder, can you give me the config file you are using?

**Comment by Koralion** [comment]
i found a mistake i did and added the Test.informaive:false now both the Demo and training show both the same error

  File "/home/adrian/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 34, in __init__
    pred_prop = statistics['pred_freq']
                ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'pred_freq'


Hope you can help me

**Comment by Maelic** [comment]
Hi @Koralion,

Which version of the codebase are you running? The 'pred_freq' variable should be computed here in your code:
https://github.com/Maelic/SGG-Benchmark/blob/99777427317f4b80e5b3ce42eb45c6ceebdb852e/sgg_benchmark/data/datasets/visual_genome.py#L141

Please update to the latest version and try again `git pull && pip install .`
What you may also need to do is delete the cache file for dataset statistics because it is not re-build every time, so if you are using the same output path with a different version you may have this kind of issue. Please delete the file named like this `VG_stanford_filtered_with_attribute_train_statistics.cache` in your checkpoint path (in `upload_causal_motif_sgdet` directory if you are using the provided checkpoint) and try again, the statistics will be re-computed automatically if the cache file is not found.

**Comment by Koralion** [comment]
Okay i just did a fresh install and just changed the paths 

this resulted in 
Traceback (most recent call last):
```
  File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 475, in <module>
    main()
  File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 418, in main
    cfg.merge_from_file(args.config_file)
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_HEADS.USE_FPN'
```

i tried to fix it by adding 

`cfg.set_new_allowed(True) # recursively update set_new_allowed to allow merging of configs and subconfigs`

ahead of line 418 in relation_test_net.py

which resulted in the earlier error

    pred_prop = statistics['pred_freq']
                ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'pred_freq'


So i expect it is something with the GCL_SETTING?

**Comment by Maelic** [comment]
> Okay i just did a fresh install and just changed the paths
> 
> this resulted in Traceback (most recent call last):
> 
> ```
>   File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 475, in <module>
>     main()
>   File "/home/adrian/SGG-Benchmark/tools/relation_train_net.py", line 418, in main
>     cfg.merge_from_file(args.config_file)
>   File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 213, in merge_from_file
>     self.merge_from_other_cfg(cfg)
>   File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
>     _merge_a_into_b(cfg_other, self, self, [])
>   File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
>     _merge_a_into_b(v, b[k], root, key_list + [k])
>   File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
>     _merge_a_into_b(v, b[k], root, key_list + [k])
>   File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/yacs/config.py", line 491, in _merge_a_into_b
>     raise KeyError("Non-existent config key: {}".format(full_key))
> KeyError: 'Non-existent config key: MODEL.ROI_HEADS.USE_FPN'
> ```
> 
> i tried to fix it by adding
> 
> `cfg.set_new_allowed(True) # recursively update set_new_allowed to allow merging of configs and subconfigs`
> 
> ahead of line 418 in relation_train_net.py
> 
> which resulted in the earlier error
> 
> ```
> pred_prop = statistics['pred_freq']
>             ~~~~~~~~~~^^^^^^^^^^^^^
> ```
> 
> KeyError: 'pred_freq'
> 
> So i expect it is something with the GCL_SETTING?

Sorry I didn't update the config file, basically I made several changes to the config args, so the config file from the checkpoint of Kahuia (the `upload_causal_motif_sgdet` checkpoint) will not work anymore.
I have just uploaded a better config file that should work for your case, please adjust the "GLOVE_DIR" path to your glove directory inside the following file and run the demo with it:
[configs/VG150/baseline/demo_motifs_faster_rcnn.yaml](configs/VG150/baseline/demo_motifs_faster_rcnn.yaml)

In the next few days I will try to clean this up and provide my own checkpoint with improved results to make it easier.

**Comment by Koralion** [comment]
That's what I expected 

The Demo showed following error

  File "/home/adrian/SGG-Benchmark/demo/webcam_demo.py", line 68, in <module>
    main(args)
  File "/home/adrian/SGG-Benchmark/demo/webcam_demo.py", line 19, in main
    model = SGG_Model(config_path, dict_file, weights, tracking=tracking, rel_conf=rel_conf, box_conf=box_conf)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 59, in __init__
    self.load_model()
  File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 64, in load_model
    self.model = build_detection_model(self.cfg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/modeling/detector/detectors.py", line 11, in build_detection_model
    return meta_arch(cfg)
           ^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/modeling/detector/generalized_rcnn.py", line 31, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.out_channels)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/modeling/roi_heads/roi_heads.py", line 71, in build_roi_heads
    roi_heads.append(("relation", build_roi_relation_head(cfg, in_channels)))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 114, in build_roi_relation_head
    return ROIRelationHead(cfg, in_channels)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 33, in __init__
    statistics = get_dataset_statistics(cfg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/data/build.py", line 53, in get_dataset_statistics
    dataset = factory(**args)
              ^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/data/datasets/visual_genome.py", line 67, in __init__
    self.get_custom_imgs(custom_path)
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/sgg_benchmark/data/datasets/visual_genome.py", line 176, in get_custom_imgs
    img = Image.open(os.path.join(path, file_name)).convert("RGB")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.conda/envs/sgg_benchmark/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './profiling.ipynb'



But it is fine I can wait a few days thanks for the quick responses!

**Comment by Maelic** [comment]
I fixed the issue, should work now with a pull and re-build.

**Comment by Koralion** [comment]
resulted in Key error 
  File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 213, in _post_process
    current_dict['rel_labels'] = [self.stats['idx_to_predicate'][str(i)] for i in current_dict['rel_labels']]
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 213, in <listcomp>
    current_dict['rel_labels'] = [self.stats['idx_to_predicate'][str(i)] for i in current_dict['rel_labels']]
                                  ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'idx_to_predicate'


It is the same for line 212 with the idx_to_label

when I commented out these two lines the demo worked but obviously without labels

**Comment by Maelic** [comment]
> resulted in Key error File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 213, in _post_process current_dict['rel_labels'] = [self.stats['idx_to_predicate'][str(i)] for i in current_dict['rel_labels']] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 213, in current_dict['rel_labels'] = [self.stats['idx_to_predicate'][str(i)] for i in current_dict['rel_labels']] ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'idx_to_predicate'
> 
> It is the same for line 212 with the idx_to_label
> 
> when I commented out these two lines the demo worked but obviously without labels

Please check that the path to the dict file is correct (argument `--classes`). Check that your dict file contains the correct keys.

**Comment by Maelic** [comment]
Oh my bad I forgot to include the dict file in the datasets folder, should work now with the file [https://github.com/Maelic/SGG-Benchmark/blob/main/datasets/vg/VG-SGG-dicts-with-attri.json](https://github.com/Maelic/SGG-Benchmark/blob/main/datasets/vg/VG-SGG-dicts-with-attri.json) as the --classes argument.

**Comment by Koralion** [comment]
Okay it worked!
Traceback (most recent call last):
  File "/home/adrian/SGG-Benchmark/demo/webcam_demo.py", line 63, in <module>
    main(args)
  File "/home/adrian/SGG-Benchmark/demo/webcam_demo.py", line 29, in main
    img, graph = model.predict(frame, visu=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/SGG-Benchmark/demo/demo_model.py", line 100, in predict
    for i, cur_id in enumerate(tracks[:,6]):
                               ~~~~~~^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

This happend after like a minute of testing, but that might also be from my setup(using my smartphone with democam as a webcam)
But again thanks for your help!

**Comment by Maelic** [comment]
Glad it worked for you! 
I'm closing this issue now, don't hesitate to open a new one if you encounter any other issues!
