### ISSUE TITLE
Non-existent config key: MODEL.ROI_RELATION_HEAD.USE_SPATIAL_FEATURES'

### ISSUE THREAD

**Issue by wudibadan** [Maelic/SGG-Benchmark#40]
Thank you very much for your work. I encountered an issue and would like to ask for your assistance. I trained using the configuration file SGG-Benchmark-main/configs/VG150/e2e_relation_yolov8m.yaml, but when I ran the demo, I encountered the following error: Non-existent config key: MODEL.ROI_RELATION_HEAD.USE_SPATIAL_FEATURES. Could you please advise on how to resolve this issue?

/data3/2024/SGG-Benchmark-main/demo$ python webcam_demo.py --classes /data3/2024/SGG-Benchmark-main/datasets/vg/VG-SGG-dicts-with-attri.json --config /data3/2024/SGG-Benchmark-main/configs/VG150/e2e_relation_yolov8m.yaml --weights /data3/2024/SGG-Benchmark-main/checkpoints/motif-precls-exmp/best_model_epoch_5.pth --tracking 
Traceback (most recent call last):
  File "/data3/2024SGG-Benchmark-main/demo/webcam_demo.py", line 66, in <module>
    main(args)
  File "/data3/2024SGG-Benchmark-main/demo/webcam_demo.py", line 19, in main
    model = SGG_Model(config_path, dict_file, weights, tracking=tracking, rel_conf=rel_conf, box_conf=box_conf)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data3/2024/SGG-Benchmark-main/demo/demo_model.py", line 21, in __init__
    cfg.merge_from_file(config)
  File "/data1/anaconda3/envs/sggb/lib/python3.11/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/data1/anaconda3/envs/sggb/lib/python3.11/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/data1/anaconda3/envs/sggb/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/data1/anaconda3/envs/sggb/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/data1/anaconda3/envs/sggb/lib/python3.11/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_RELATION_HEAD.USE_SPATIAL_FEATURES'

**Comment by Maelic** [comment]
Yes, you can remove the key ` MODEL.ROI_RELATION_HEAD.USE_SPATIAL_FEATURES` from the e2e_relation_yolov8m.yaml file, it is not used anymore.

**Comment by wudibadan** [comment]
> 是的，您可以从 e2e_relation_yolov8m.yaml 文件中删除密钥，它不再使用。` MODEL.ROI_RELATION_HEAD.USE_SPATIAL_FEATURES`

Thank you very much for your response. I also wanted to ask, although I defined the training for 20 epochs, the training automatically stops after a few epochs. Could you please let me know if there’s any mechanism that causes this?

**Comment by Maelic** [comment]
Yes, I use early stopping with a `WarmupReduceLROnPlateau` scheduler to stop the training after a few epochs with no improvements. You can customize this behavior by modifying the variables `COOLDOWN`, `MAX_DECAY_STEP`, and `PATIENCE` in the config file. See [this file](https://github.com/Maelic/SGG-Benchmark/blob/286e1c14e26e653ac51811391b81dc2cdd136d23/sgg_benchmark/solver/lr_scheduler.py#L68) for reference.
