### ISSUE TITLE
YOLOv8m-world Issues for SGDet

### ISSUE THREAD

**Issue by grapesonwang** [Maelic/SGG-Benchmark#46]
Hi, 

**I followed your notebook to convert a yolov8m-world model to the VG150K dataset, but I have encountered some issues. I have also attached the config file in the end for you to look over. Please give me some advice on this. Thank you!

Best wishes,**

2024-12-20 11:17:36.510 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2024-12-20 11:17:36.510 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2024-12-20 11:17:36.514 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:42 - Loading data statistics from: ./checkpoints/react_final/VG150_train_statistics.cache
2024-12-20 11:17:36.514 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:43 - ----------------------------------------------------------------------------------------------------
2024-12-20 11:17:50.291 | INFO     | __main__:main:71 - Loading last checkpoint from ./checkpoints/react_final/best_model_epoch_9.pth...
2024-12-20 11:17:50.291 | INFO     | sgg_benchmark.utils.checkpoint:load:72 - Loading checkpoint from ./checkpoints/react_final/best_model_epoch_9.pth
2024-12-20 11:17:50.692 | INFO     | sgg_benchmark.utils.checkpoint:_load_file:343 - WorldModel detected in checkpoint. Extracting state_dict...
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/tools/relation_test_net.py", line 176, in <module>
    main()
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/tools/relation_test_net.py", line 72, in main
    _ = checkpointer.load(last_check)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/sgg_benchmark/utils/checkpoint.py", line 82, in load
    self._load_model(checkpoint, load_mapping, verbose)
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/sgg_benchmark/utils/checkpoint.py", line 180, in _load_model
    load_state_dict(self.model, state_dict, load_mapping, verbose)
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/sgg_benchmark/utils/model_serialization.py", line 94, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeneralizedYOLO:
	size mismatch for backbone.model.22.cv4.0.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for backbone.model.22.cv4.1.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for backbone.model.22.cv4.2.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
[2024-12-20 11:17:56,297] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 52301) of binary: /usr/local/envs/sgg_benchmark/bin/python
Traceback (most recent call last):
  File "/usr/local/envs/sgg_benchmark/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

**Below are the configurations**
============================================================================
INPUT:
  MIN_SIZE_TRAIN: 640
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640
  PADDING: True
MODEL:
  TEXT_EMBEDDING: clip
  META_ARCHITECTURE: "GeneralizedYOLO"
  BOX_HEAD: False
  WEIGHT: ""
  PRETRAINED_DETECTOR_CKPT: "content/gdrive/MyDrive/SGG-Benchmark-PW/checkpoints/react_final/best_model_epoch_9.pth"
  BACKBONE:
    TYPE: "yolov8world"
    NMS_THRESH: 0.001
    FREEZE: True
  YOLO:
    SIZE: "yolov8m-worldv2"
    OUT_CHANNELS: 192 # 192 for yolov8m, 256 for yolov8l
  RELATION_ON: True
  ATTRIBUTE_ON: False
  FLIP_AUG: False            # if there is any left-right relation, FLIP AUG should be false
  ROI_HEADS:
    POSITIVE_FRACTION: 0.5
    FG_IOU_THRESHOLD: 0.3
    BG_IOU_THRESHOLD: 0.1
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 40
    NMS_FILTER_DUPLICATES: True
    NMS: 0.2
  ROI_BOX_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125)
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "YOLOV8FeatureExtractor"
    NUM_CLASSES: 151              # 151 for VG, 1201 for GQA
  ROI_RELATION_HEAD:
    EMBED_DIM: 512
    USE_GT_BOX: False
    USE_GT_OBJECT_LABEL: False
    USE_SPATIAL_FEATURES: False
    REQUIRE_BOX_OVERLAP: False              # for sgdet, during training, only train pairs with overlap
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: True    # for sgdet only, in case some gt boxes are missing
    NUM_CLASSES: 51                 # 51 for VG, 201 for GQA (not contain "to the left of" & "to the right of")
    BATCH_SIZE_PER_IMAGE: 256      # sample as much as possible
    POSITIVE_FRACTION: 0.25
    CONTEXT_POOLING_DIM: 2048
    CONTEXT_HIDDEN_DIM: 512         #1024 for VCTree
    POOLING_ALL_LEVELS: True
    LABEL_SMOOTHING_LOSS: False
    FEATURE_EXTRACTOR: "RelationFeatureExtractor"
    #################### Select Relationship Model ####################
    #PREDICTOR: "MotifPredictor"
    #PREDICTOR: "VCTreePredictor"
    #PREDICTOR: "TransformerPredictor"
    # PREDICTOR: "CausalAnalysisPredictor"
    PREDICTOR: "REACTPredictor"
    ################# Parameters for Motif Predictor ##################
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_REL_LAYER: 1
    ############# Parameters for Causal Unbias Predictor ##############
    ### Implementation for paper "Unbiased Scene Graph Generation from Biased Training"
    CAUSAL:
      EFFECT_TYPE: 'TDE'             # candicates: 'TDE', 'NIE', 'TE', 'none'
      FUSION_TYPE: 'sum'              # candicates: 'sum', 'gate'         
      SEPARATE_SPATIAL: False         # separate spatial in union feature
      CONTEXT_LAYER: "motifs"         # candicates: motifs, vctree, vtranse
      EFFECT_ANALYSIS: True
    ############### Parameters for Transformer Predictor ##############
    TRANSFORMER:
      DROPOUT_RATE: 0.1
      OBJ_LAYER: 4
      REL_LAYER: 2
      NUM_HEAD: 8
      KEY_DIM: 64
      VAL_DIM: 64
      INNER_DIM: 2048 
DATASETS:
  TRAIN: ("VG150_train",)
  VAL: ("VG150_val",)
  TEST: ("VG150_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  MAX_EPOCH: 20
  BIAS_LR_FACTOR: 1
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 5.0
  STEPS: (10000, 16000)
  MAX_ITER: 40000
  VAL_PERIOD: 2000
  CHECKPOINT_PERIOD: 2000
  PRINT_GRAD_FREQ: 4000
  SCHEDULE:
    # the following paramters are only used for WarmupReduceLROnPlateau
    TYPE: "WarmupReduceLROnPlateau"    # WarmupMultiStepLR, WarmupReduceLROnPlateau
    PATIENCE: 2
    THRESHOLD: 0.001
    COOLDOWN: 0
    FACTOR: 0.1
    MAX_DECAY_STEP: 3
OUTPUT_DIR: './output/relation_baseline'
TEST:
  ALLOW_LOAD_FROM_CACHE: False
  INFORMATIVE: True
  RELATION:
    SYNC_GATHER: True      # turn on will slow down the evaluation to solve the sgdet test out of memory problem
    REQUIRE_OVERLAP: True
    LATER_NMS_PREDICTION_THRES: 0.5
  CUSTUM_EVAL: False       # eval SGDet model on custum images, output a json
  CUSTUM_PATH: '.'         # the folder that contains the custum images, only jpg files are allowed

**Comment by Maelic** [comment]
Hello, 
It seems that the PRETRAINED_DETECTOR_CKPT variable of your config file is wrong, it should be the YoloWorld model in`.pt` generated by my notebook. So something like that:
`PRETRAINED_DETECTOR_CKPT: "custom_yolov8m_vg150.pt"`
The variable `PRETRAINED_DETECTOR_CKPT` is used to initialize the object detection model only, however, the checkpoint `react_final/best_model_epoch_9.pth` is an SGG model (i.e. object detection + relation prediction) so it will not work here.

**Comment by ZHUXUHAN** [comment]
> Hello, It seems that the PRETRAINED_DETECTOR_CKPT variable of your config file is wrong, it should be the YoloWorld model in`.pt` generated by my notebook. So something like that: `PRETRAINED_DETECTOR_CKPT: "custom_yolov8m_vg150.pt"` The variable `PRETRAINED_DETECTOR_CKPT` is used to initialize the object detection model only, however, the checkpoint `react_final/best_model_epoch_9.pth` is an SGG model (i.e. object detection + relation prediction) so it will not work here.

how can we download the yoloworld model?

**Comment by Maelic** [comment]
I don't provide a download link for yolo-world because the model can easily be generated in 2min. Please install the ultralytics package and follow [my notebook](https://github.com/Maelic/SGG-Benchmark/blob/main/process_data/yolo_world.ipynb) to generate the weights.

**Comment by Maelic** [comment]
The notebook is an example with the VG150 dataset but you can change the classes with your own dataset as well.

**Comment by ZHUXUHAN** [comment]
I see, thanks, you answers help me a lot.

**Comment by PengPaulWang** [comment]
> Hello, It seems that the PRETRAINED_DETECTOR_CKPT variable of your config file is wrong, it should be the YoloWorld model in`.pt` generated by my notebook. So something like that: `PRETRAINED_DETECTOR_CKPT: "custom_yolov8m_vg150.pt"` The variable `PRETRAINED_DETECTOR_CKPT` is used to initialize the object detection model only, however, the checkpoint `react_final/best_model_epoch_9.pth` is an SGG model (i.e. object detection + relation prediction) so it will not work here.

Thank you! 

react_final/best_model_epoch_9.pth was actually a YoloWorld model, i just changed the name as it did not work in the first place so I changed the name to avoid any potential name issues.

I did not use your notebook to generate the YOLOWorld model though. Is it like we have to have 150 classes? Can I define new classes through your notebook or the ultralytics? I tried, but did not work.

**Comment by PengPaulWang** [comment]
> I see, thanks, you answers help me a lot.

Have you made it work?

**Comment by Maelic** [comment]
> > Hello, It seems that the PRETRAINED_DETECTOR_CKPT variable of your config file is wrong, it should be the YoloWorld model in`.pt` generated by my notebook. So something like that: `PRETRAINED_DETECTOR_CKPT: "custom_yolov8m_vg150.pt"` The variable `PRETRAINED_DETECTOR_CKPT` is used to initialize the object detection model only, however, the checkpoint `react_final/best_model_epoch_9.pth` is an SGG model (i.e. object detection + relation prediction) so it will not work here.
> 
> Thank you!
> 
> react_final/best_model_epoch_9.pth was actually a YoloWorld model, i just changed the name as it did not work in the first place so I changed the name to avoid any potential name issues.
> 
> I did not use your notebook to generate the YOLOWorld model though. Is it like we have to have 150 classes? Can I define new classes through your notebook or the ultralytics? I tried, but did not work.

Yes you can define any classes you want with yolo-world (not necessarily 150), but you have to make sure that the class names and order match with the SGG annotations of your dataset (the `VG-SGG-dicts.json` type file). In my notebook, I take the class names directly from the `.json` file to avoid any confusion.
You can have a look at the ultralytics documentation if you want more details.

**Comment by PengPaulWang** [comment]
> > > Hello, It seems that the PRETRAINED_DETECTOR_CKPT variable of your config file is wrong, it should be the YoloWorld model in`.pt` generated by my notebook. So something like that: `PRETRAINED_DETECTOR_CKPT: "custom_yolov8m_vg150.pt"` The variable `PRETRAINED_DETECTOR_CKPT` is used to initialize the object detection model only, however, the checkpoint `react_final/best_model_epoch_9.pth` is an SGG model (i.e. object detection + relation prediction) so it will not work here.
> > 
> > 
> > Thank you!
> > react_final/best_model_epoch_9.pth was actually a YoloWorld model, i just changed the name as it did not work in the first place so I changed the name to avoid any potential name issues.
> > I did not use your notebook to generate the YOLOWorld model though. Is it like we have to have 150 classes? Can I define new classes through your notebook or the ultralytics? I tried, but did not work.
> 
> Yes you can define any classes you want with yolo-world (not necessarily 150), but you have to make sure that the class names and order match with the SGG annotations of your dataset (the `VG-SGG-dicts.json` type file). In my notebook, I take the class names directly from the `.json` file to avoid any confusion. You can have a look at the ultralytics documentation if you want more details.

==================================================================================================
**checked everything really but still got the following errors.**

can you help to check if my commands to run it is correct?

!source activate sgg_benchmark && CUDA_VISIBLE_DEVICES=0 torchrun --master_port 10027 --nproc_per_node=1 tools/relation_test_net.py --config-file "./configs/VG150/e2e_relation_yolov8x_world_react.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX False MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR REACTPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE vctree MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE gate MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER TDE TEST.IMS_PER_BATCH 1 DTYPE "float16" GLOVE_DIR ./glove_yolo8m MODEL.PRETRAINED_DETECTOR_CKPT ./checkpoints/react_final OUTPUT_DIR ./checkpoints/react_final TEST.CUSTUM_EVAL True TEST.CUSTUM_PATH ./checkpoints/react_final/react_custom_images DETECTED_SGG_DIR ./checkpoints/react_final/react_detected_yolov8m


##########################

2025-01-08 14:22:12.763 | INFO     | sgg_benchmark.utils.logger:setup_logger:31 - Using loguru logger with level: INFO
2025-01-08 14:22:12.763 | INFO     | __main__:main:50 - Using 1 GPUs
2025-01-08 14:22:12.763 | INFO     | sgg_benchmark.utils.logger:logger_step:15 - #################### Step 1: Collecting environment info... ####################
Overriding model.yaml nc=80 with nc=150

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]           
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   8670410  ultralytics.nn.modules.block.C2fAttn         [1280, 640, 3, 320, 10]       
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   2312805  ultralytics.nn.modules.block.C2fAttn         [960, 320, 3, 160, 5]         
 16                  15  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   8465610  ultralytics.nn.modules.block.C2fAttn         [960, 640, 3, 320, 10]        
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   8670410  ultralytics.nn.modules.block.C2fAttn         [1280, 640, 3, 320, 10]       
 22        [15, 18, 21]  1   9214102  ultralytics.nn.modules.head.WorldDetect      [150, 512, True, [320, 640, 640]]
YOLOv8x-worldv2 summary: 396 layers, 72,886,377 parameters, 72,886,361 gradients, 341.4 GFLOPs

2025-01-08 14:22:14.552 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:30 - ----------------------------------------------------------------------------------------------------
2025-01-08 14:22:14.552 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:31 - get dataset statistics...
2025-01-08 14:22:14.555 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:46 - Unable to load data statistics from: ./checkpoints/react_final/VG150_train_statistics.cache
2025-01-08 14:24:35.617 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:71 - Save data statistics to: ./checkpoints/react_final/VG150_train_statistics.cache
2025-01-08 14:24:35.617 | INFO     | sgg_benchmark.data.build:get_dataset_statistics:72 - ----------------------------------------------------------------------------------------------------
2025-01-08 14:25:40.413 | INFO     | __main__:main:71 - Loading last checkpoint from ./checkpoints/react_final/custom_yolov8x_vg150.pt...
2025-01-08 14:25:40.413 | INFO     | sgg_benchmark.utils.checkpoint:load:68 - Loading checkpoint from ./checkpoints/react_final/custom_yolov8x_vg150.pt
2025-01-08 14:25:40.917 | INFO     | sgg_benchmark.utils.checkpoint:_load_file:208 - WorldModel detected in checkpoint. Extracting state_dict...
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/tools/relation_test_net.py", line 176, in <module>
    main()
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/tools/relation_test_net.py", line 72, in main
    _ = checkpointer.load(last_check)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/sgg_benchmark/utils/checkpoint.py", line 70, in load
    self._load_model(checkpoint, load_mapping, verbose)
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/sgg_benchmark/utils/checkpoint.py", line 110, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"), load_mapping, verbose)
  File "/content/gdrive/MyDrive/SGG-Benchmark-PW/sgg_benchmark/utils/model_serialization.py", line 94, in load_state_dict
    model.load_state_dict(model_state_dict,strict=False)
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeneralizedYOLO:
	size mismatch for backbone.model.22.cv4.0.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for backbone.model.22.cv4.1.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for backbone.model.22.cv4.2.bias: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).
[2025-01-08 14:25:43,759] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 10731) of binary: /usr/local/envs/sgg_benchmark/bin/python
Traceback (most recent call last):
  File "/usr/local/envs/sgg_benchmark/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/envs/sgg_benchmark/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/relation_test_net.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-08_14:25:43
  host      : 8f5a1825ce76
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10731)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Maelic** [comment]
It seems that you are trying to initialize the model with the wrong weights, make sure that you have trained an SGG model and saved it correctly (using the last_checkpoint.txt file) before trying to run `relation_test_net.py`. Your SGG model should be in `.pth` format. It seems that the model you are trying to load is `custom_yolov8x_vg150.pt` which is only the object detector and not the full SGG model.
