### ISSUE TITLE
low mAP when training on sgcls and sgdet task 

### ISSUE THREAD

**Issue by A11en4z** [Maelic/SGG-Benchmark#48]
hello, I trained yolov8m on my own dataset ，and it works fine on the predcls task, but I'm having problems trying the sgcls and sgdet tasks,could you please help me with that and make some suggestions?
Description of the problem：very low mAP 
on sgcls  task : 
![image](https://github.com/user-attachments/assets/75b950ec-67ab-42ec-8df1-d92506303143)
![image](https://github.com/user-attachments/assets/9464648b-49ff-4e69-8dc5-cdd274ab063d)

on sgdet task:
![image](https://github.com/user-attachments/assets/efe06f54-ea6e-490d-ab76-219e6cacfd1e)

Then I tried detector_pretest_net.py ，and got same low mAP
![image](https://github.com/user-attachments/assets/1ce026ca-cd40-4990-bc49-5b46001d34ea)

Additionally, I tried the Fasterrcnn checkpoint trained from Scene Graph Benchmark, and the results were also close to 0.

It's very confusing and I don't know what to do .

Below is my config:
INPUT:
  MIN_SIZE_TRAIN: 1024
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 1024
  PADDING: True
MODEL:
  TEXT_EMBEDDING: glove.6B
  META_ARCHITECTURE: "GeneralizedYOLO"
  BOX_HEAD: False 
  WEIGHT: ""
  PRETRAINED_DETECTOR_CKPT: "/root/autodl-tmp/ultralytics/runs/train/exp2/weights/best_test612.pt"
  #"/root/autodl-tmp/pretrain_checkpoint/v8m_last.pt"
  #"/root/autodl-tmp/ultralytics/runs/train/exp2/weights/best_test612.pt"
  #"/root/autodl-tmp/pretrain_checkpoint/best.pt" #"/home/maelic/Documents/PhD/MyModel/SGG-Benchmark/checkpoints/VG150/Backbones/yolov8m/weights/best.pt"
  BACKBONE:
    TYPE: "yolov8"
    NMS_THRESH: 0.001
    FREEZE: True
  YOLO:
    SIZE: "yolov8m" #"yolov8m"
    OUT_CHANNELS: 192 #64  #192 # 192 for yolov8m, 256 for yolov8l
  RELATION_ON: True
  ATTRIBUTE_ON: False
  FLIP_AUG: False            # if there is any left-right relation, FLIP AUG should be false
  ROI_HEADS:
    POSITIVE_FRACTION: 0.5
    FG_IOU_THRESHOLD: 0.3
    BG_IOU_THRESHOLD: 0.1
    BATCH_SIZE_PER_IMAGE: 256
    DETECTIONS_PER_IMG: 80
    NMS_FILTER_DUPLICATES: True
    NMS: 0.2
  ROI_BOX_HEAD:
    POOLER_SCALES: (0.125, 0.0625, 0.03125)
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "YOLOV8FeatureExtractor"
    NUM_CLASSES: 31 #151              # 151 for VG, 1201 for GQA
  ROI_RELATION_HEAD:
    EMBED_DIM: 200
    USE_GT_BOX: False
    USE_GT_OBJECT_LABEL: False
    USE_SPATIAL_FEATURES: True
    REQUIRE_BOX_OVERLAP: False              # for sgdet, during training, only train pairs with overlap
    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: True    # for sgdet only, in case some gt boxes are missing
    NUM_CLASSES: 42 #51                 # 51 for VG, 201 for GQA (not contain "to the left of" & "to the right of")
    BATCH_SIZE_PER_IMAGE: 256      # sample as much as possible
    POSITIVE_FRACTION: 0.25
    CONTEXT_POOLING_DIM: 2048
    CONTEXT_HIDDEN_DIM: 512         #1024 for VCTree
    POOLING_ALL_LEVELS: True
    LABEL_SMOOTHING_LOSS: False
    FEATURE_EXTRACTOR: "RelationFeatureExtractor"
    #################### Select Relationship Model ####################
    #PREDICTOR: "MotifPredictor"
    #PREDICTOR: "VCTreePredictor"
    #PREDICTOR: "TransformerPredictor"
    PREDICTOR: "CausalAnalysisPredictor"
    ################# Parameters for Motif Predictor ##################
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_REL_LAYER: 1
    ############# Parameters for Causal Unbias Predictor ##############
    ### Implementation for paper "Unbiased Scene Graph Generation from Biased Training"
    CAUSAL:
      EFFECT_TYPE: 'TDE'             # candicates: 'TDE', 'NIE', 'TE', 'none'
      FUSION_TYPE: 'sum'              # candicates: 'sum', 'gate'         
      SEPARATE_SPATIAL: False         # separate spatial in union feature
      CONTEXT_LAYER: "motifs"         # candicates: motifs, vctree, vtranse
      EFFECT_ANALYSIS: True
    ############### Parameters for Transformer Predictor ##############
    TRANSFORMER:
      DROPOUT_RATE: 0.1
      OBJ_LAYER: 4
      REL_LAYER: 2
      NUM_HEAD: 8
      KEY_DIM: 64
      VAL_DIM: 64
      INNER_DIM: 2048 
DATASETS:
  TRAIN: ("VG150_train",)
  VAL: ("VG150_val",)
  TEST: ("VG150_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  MAX_EPOCH: 20
  BIAS_LR_FACTOR: 1
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 5.0
  STEPS: (10000, 16000)
  MAX_ITER: 40000
  VAL_PERIOD: 2000
  CHECKPOINT_PERIOD: 2000
  PRINT_GRAD_FREQ: 4000
  SCHEDULE:
    # the following paramters are only used for WarmupReduceLROnPlateau
    TYPE: "WarmupReduceLROnPlateau"    # WarmupMultiStepLR, WarmupReduceLROnPlateau
    PATIENCE: 2
    THRESHOLD: 0.001
    COOLDOWN: 0
    FACTOR: 0.1
    MAX_DECAY_STEP: 3
OUTPUT_DIR: '/root/checkpoints/sgdet/motifs-yolov8m' #'/root/autodl-tmp/checkpoints/Predcls/motifs-yolov8n'
TEST:
  ALLOW_LOAD_FROM_CACHE: False
  INFORMATIVE: False #True
  RELATION:
    SYNC_GATHER: True      # turn on will slow down the evaluation to solve the sgdet test out of memory problem
    REQUIRE_OVERLAP: True
    LATER_NMS_PREDICTION_THRES: 0.5
  CUSTUM_EVAL: False       # eval SGDet model on custum images, output a json
  CUSTUM_PATH: '.'         # the folder that contains the custum images, only jpg files are allowed  

I tried to look for similar issues in the issue and found that it might be that my version of ultralytics is not 8.2.70.I just realized that I don't seem to have changed the local ultralytics version correctly, and may still be using the checkpoint trained with the latest version of Ultralytics, could this be the cause?

looking forward to your reply !

**Comment by Maelic** [comment]
Hello,

As I said [in this issue](https://github.com/Maelic/SGG-Benchmark/issues/45), SGCls is not supported for YOLO-based models unfortunately. 
For the sgdet settings, it is hard for me to give a clear answer but from what I see it may come from the `MIN_SIZE_TRAIN` and `MAX_SIZE_TRAIN` which should be similar to the training of the Yolo model. By default YOLOV8 is trained on 640*640 size and not 1024*1024, did you change the yolo config to 1024*1024? ALso, what is the accuracy of the YOLOV8 model reported on your dataset after the ultralytics training?

**Comment by A11en4z** [comment]
> Hello,
> 
> As I said [in this issue](https://github.com/Maelic/SGG-Benchmark/issues/45), SGCls is not supported for YOLO-based models unfortunately. For the sgdet settings, it is hard for me to give a clear answer but from what I see it may come from the `MIN_SIZE_TRAIN` and `MAX_SIZE_TRAIN` which should be similar to the training of the Yolo model. By default YOLOV8 is trained on 640*640 size and not 1024*1024, did you change the yolo config to 1024*1024? Also, what is the accuracy of the YOLOV8 model reported on your dataset after the ultralytics training?

Thank you for your reply !
I used my own dataset, trained in ultralytics with imsz=1024. in ultralytics test set mAP50-95 is around 0.6.
![image](https://github.com/user-attachments/assets/dff68803-dd3e-404b-9b4d-b92c5e85bf9a)
I just tried again with the new checkpoint trained with v8.2.70, and it's exactly the same as the original results, and I'm wondering if there's something wrong with my config settings.

When I test my detection model with pretest_net.py, I modify the 
BOX_HEAD: True
RELATION_ON: False
and get an error reported:

Traceback (most recent call last):
  File "/root/autodl-tmp/SGG-Benchmark/tools/detector_pretest_net.py", line 172, in <module>
    main()
  File "/root/autodl-tmp/SGG-Benchmark/tools/detector_pretest_net.py", line 156, in main
    inference(
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 273, in inference
    predictions, timings, timings2 = compute_on_dataset(model, data_loader, device, synchronize_gather=cfg.TEST.RELATION.SYNC_GATHER, timer=True, silence=silence, informative=False)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/engine/inference.py", line 48, in compute_on_dataset
    output = model(images.to(device), targets)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/detector/generalized_yolo.py", line 84, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets, logger, proposals)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/roi_heads.py", line 25, in forward
    x, detections, loss_box = self.box(features, proposals, targets)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/box_head/box_head.py", line 91, in forward
    class_logits, box_regression = self.predictor(x)
                                   ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SGG-Benchmark/sgg_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py", line 28, in forward
    cls_logit = self.cls_score(x)
                ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sgg/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1 and 2048x31)

I replaced the checkpoint training sgdet trained on v8.2.70 and the results are still exactly the same.
![image](https://github.com/user-attachments/assets/a11e18f5-8dd2-4c5f-aab1-0252934f943b)

**Comment by Maelic** [comment]
I am not sure if the pretest_net.py script still works with the new architecture to be honest, I haven't used it for a while.
Can you try using relation_train_net.py script with the `SOLVER.PRE_VAL True` argument and see if you have the same error?
As you say, something could also be wrong with your dataset. Try to make sure that your box annotations are in the correct format, which is something like [center_x, center_y, w, h] by default for VG format.

**Comment by A11en4z** [comment]
> I am not sure if the pretest_net.py script still works with the new architecture to be honest, I haven't used it for a while. Can you try using relation_train_net.py script with the `SOLVER.PRE_VAL True` argument and see if you have the same error? As you say, something could also be wrong with your dataset. Try to make sure that your box annotations are in the correct format, which is something like [center_x, center_y, w, h] by default for VG format.

Yes, you are right .
I was trying to pre-train the target detector on the full dataset and then do the relationship prediction on a subset, but the results on the subset were just close to 0. I just replaced the dataset with the full dataset and it's results became normal, there are still new errors reported, but that makes me feel much better :).
![image](https://github.com/user-attachments/assets/eb394bcf-3a3a-4bf5-878e-c08343eb3e2c)

**Comment by A11en4z** [comment]
@Maelic Thank you very much for your kind reply, it really helped me a lot !!!

**Comment by Maelic** [comment]
I am not sure to understand what you are trying to do but you can't pre-train the Yolo detector using my codebase as you would do with faster-rcnn. You can only pre-trained YOLO using the ultralytics codebase.

Glad to know I could help you and good luck with your project :)
