### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.ROI_HEADS.USE_FPN'

### ISSUE THREAD

**Issue by NilBiescas** [Maelic/SGG-Benchmark#7]
I'm trying to run SGDET_on_cutom_images.ipynb and I'm getting the followign error: 
Traceback (most recent call last):
  File "/home/nbiescas/Desktop/SGG-Benchmark/tools/relation_test_net.py", line 130, in <module>
    main()
  File "/home/nbiescas/Desktop/SGG-Benchmark/tools/relation_test_net.py", line 42, in main
    cfg.merge_from_file(args.config_file)
  File "/home/nbiescas/miniconda3/envs/scene_graph_benchmark/lib/python3.11/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/nbiescas/miniconda3/envs/scene_graph_benchmark/lib/python3.11/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/nbiescas/miniconda3/envs/scene_graph_benchmark/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/nbiescas/miniconda3/envs/scene_graph_benchmark/lib/python3.11/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/nbiescas/miniconda3/envs/scene_graph_benchmark/lib/python3.11/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_HEADS.USE_FPN'

I'm using this command and also getting the same error:
CUDA_VISIBLE_DEVICES=0 python tools/relation_test_net.py --config-file "/home/nbiescas/Desktop/SGG-Benchmark/configs/VG150/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX False MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE TDE MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs TEST.IMS_PER_BATCH 1 DTYPE "float16"  GLOVE_DIR /home/nbiescas/Desktop/Scene_Graph_Generation/Glove MODEL.PRETRAINED_DETECTOR_CKPT /home/nbiescas/Desktop/SGG-Benchmark/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR /home/nbiescas/Desktop/Scene_Graph_Generation/causal-motifs-sgdet TEST.CUSTUM_EVAL True TEST.CUSTUM_PATH /home/nbiescas/Desktop/Scene_Graph_Generation/src/DATA/EVAL/sensei-fs/users/yanzhez/REval DETECTED_SGG_DIR /home/nbiescas/Desktop/SGG-Benchmark/output_dir

It seems that in sgg_benchmark/config/defaults.py there is not definition of MODEL.ROI_HEADS.USE_FPN and that might be causing the erorr. Do you know how can i solve it ?

**Comment by NilBiescas** [comment]
adding _C.MODEL.ROI_HEADS.USE_FPN = True in the deafults.py solved but I don't know if it is the expected behaviour.
